### ISSUE TITLE
only getting sound notification, not the visual in the notification bar at top of android. Unity 5.2

### ISSUE THREAD

**Issue by TargetSlot** [Agasper/unity-android-notifications#8]

**Comment by Agasper** [comment]
Ensure that you put notification icon into **res** directory (like in the example)

**Comment by TargetSlot** [comment]
I opened your example. it does not work on Unity 5.2

**Comment by TargetSlot** [comment]
I renamed 'res' folder... after renamed back - working)

**Comment by TargetSlot** [comment]
I added icon in 'res' folder - compilation error. removed icon - working)

**Comment by TargetSlot** [comment]
Unity 5.2.3  - working

**Comment by Agasper** [comment]
I tested it with Unity 5.2.2f1 and it works
